apiVersion: v1
data:
  cloud-config: |
    instancesV2:
      enabled: true
      zoneAndRegionEnabled: true
    loadBalancer:
      creationPollInterval: 5
      creationPollTimeout: 60
    namespace: {{ .Release.Namespace }}
kind: ConfigMap
metadata:
  name: cloud-config-{{ .Release.Name }}