apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ include "machinedeployment.name" . }}
  namespace: {{ .Values.cluster.namespace }}
spec:
  clusterName: {{ include "cluster.name" . }}
  selector:
    matchLabels:
      cluster.x-k8s.io/deployment-name: {{ include "machinedeployment.name" . }}
  unhealthyConditions:
    - type: Ready
      status: "False"
      timeout: "300s"
    - type: Ready
      status: "Unknown"
      timeout: "300s"
  maxUnhealthy: "40%"
  nodeStartupTimeout: "10m"