apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubevirt
    cluster.x-k8s.io/v1alpha1: v1alpha1
    cluster.x-k8s.io/v1alpha2: v1alpha1
    cluster.x-k8s.io/v1alpha3: v1alpha1
    cluster.x-k8s.io/v1alpha4: v1alpha1
    cluster.x-k8s.io/v1beta1: v1alpha1
    clusterctl.cluster.x-k8s.io: ""
  name: capk-serving-cert
spec:
  dnsNames:
  - capk-webhook-service.{{ .Release.Namespace }}.svc
  - capk-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capk-selfsigned-issuer
  secretName: capk-webhook-service-cert