apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubevirt
    cluster.x-k8s.io/v1alpha1: v1alpha1
    cluster.x-k8s.io/v1alpha2: v1alpha1
    cluster.x-k8s.io/v1alpha3: v1alpha1
    cluster.x-k8s.io/v1alpha4: v1alpha1
    cluster.x-k8s.io/v1beta1: v1alpha1
    clusterctl.cluster.x-k8s.io: ""
    control-plane: controller-manager
  name: capk-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: kubevirt
      cluster.x-k8s.io/v1alpha1: v1alpha1
      cluster.x-k8s.io/v1alpha2: v1alpha1
      cluster.x-k8s.io/v1alpha3: v1alpha1
      cluster.x-k8s.io/v1alpha4: v1alpha1
      cluster.x-k8s.io/v1beta1: v1alpha1
      control-plane: controller-manager
  strategy: {}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: kubevirt
        cluster.x-k8s.io/v1alpha1: v1alpha1
        cluster.x-k8s.io/v1alpha2: v1alpha1
        cluster.x-k8s.io/v1alpha3: v1alpha1
        cluster.x-k8s.io/v1alpha4: v1alpha1
        cluster.x-k8s.io/v1beta1: v1alpha1
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        - --feature-gates=MachinePool=false
        command:
        - /manager
        env:
        - name: NO_PROXY
          value: 127.0.0.1,localhost
        image: '{{ .Values.images.kubevirtManager.repo }}/{{ .Values.images.kubevirtManager.name }}:{{ .Values.images.kubevirtManager.tag }}'
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        resources: {}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccountName: capk-manager
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: capk-webhook-service-cert