apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubevirt
    cluster.x-k8s.io/v1alpha1: v1alpha1
    cluster.x-k8s.io/v1alpha2: v1alpha1
    cluster.x-k8s.io/v1alpha3: v1alpha1
    cluster.x-k8s.io/v1alpha4: v1alpha1
    cluster.x-k8s.io/v1beta1: v1alpha1
    clusterctl.cluster.x-k8s.io: ""
  name: capk-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capk-leader-election-role
subjects:
- kind: ServiceAccount
  name: capk-manager
  namespace: '{{ .Release.Namespace }}'