apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/capk-serving-cert'
  labels:
    cluster.x-k8s.io/provider: infrastructure-kubevirt
    cluster.x-k8s.io/v1alpha1: v1alpha1
    cluster.x-k8s.io/v1alpha2: v1alpha1
    cluster.x-k8s.io/v1alpha3: v1alpha1
    cluster.x-k8s.io/v1alpha4: v1alpha1
    cluster.x-k8s.io/v1beta1: v1alpha1
    clusterctl.cluster.x-k8s.io: ""
  name: capk-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capk-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha1-kubevirtmachinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.kubevirtmachinetemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubevirtmachinetemplates
  sideEffects: None
